### ISSUE TITLE
Problem reading vocabularies in production environment

### ISSUE THREAD

**Issue by ijdickinson** [rdf-elixir/rdf-ex#16]
I'm trying, and failing, to deploy my working app to a production environment on fly.io. There's a write-up on the [fly.io forum here](https://community.fly.io/t/problem-reading-file-system-from-elixir-app/8210/9)

My problem comes down to the `defvocab` declarations:

```elixir
  defvocab Condition,
    base_iri: "http://example.org/def/core/habitat/",
    file: "condition.ttl"
```

The `*.ttl` vocab files are being copied to the Docker image, but are not being found by the defvocab loader. `chrismccord` from fly suggested it's because of this declaration in `vocabulary_namespace.ex`:

```elixir
  # Note: We're not using :code.priv_dir/1 here on purpose, since vocabulary files should be
  # searched in the vocabs dir of the project in which the vocabulary namespace is defined.
  @vocabs_dir "priv/vocabs"
```

Chris' suggestion is that this should, in fact, use `:code.priv_dir` because the priv dir will be in a different place in production.

As a workaround, I did also try:

```elixir
  defvocab Condition,
    base_iri: "http://example.org/def/core/habitat/",
    file: Path.join(:code.priv_dir(:myapp), "vocabs/condition.ttl")
```

But this gives a different error:

```text
ian@alder $ iex -S mix
Erlang/OTP 25 [erts-13.1.2] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit:ns]

Compiling 4 files (.ex)
Compiling vocabulary namespace for http://example.org/def/core/habitat/

== Compilation error in file lib/knowledge_graph/ns.ex ==
** (FunctionClauseError) no function clause matching in IO.chardata_to_string/1    
    
    The following arguments were given to IO.chardata_to_string/1:
    
        # 1
        {{:., [line: 40], [{:__aliases__, [line: 40], [:Path]}, :join]}, [line: 40], [{{:., [line: 40], [:code, :priv_dir]}, [line: 40], [:myapp]}, "vocabs/habitat.ttl"]}
    
    Attempted function clauses (showing 2 out of 2):
    
        def chardata_to_string(string) when is_binary(string)
        def chardata_to_string(list) when is_list(list)
    
    (elixir 1.14.1) lib/io.ex:670: IO.chardata_to_string/1
    (elixir 1.14.1) lib/file.ex:219: File.exists?/2
    (rdf 0.12.0) lib/rdf/vocabulary_namespace.ex:621: RDF.Vocabulary.Namespace.filename!/1
    (rdf 0.12.0) expanding macro: RDF.Vocabulary.Namespace.defvocab/2
    lib/knowledge_graph/ns.ex:38: KnowledgeGraph.NS (module)
```

The only other workaround I can think of at the moment is to modify the Dockerfile to copy the `*.ttl` files to a fixed well-known location, like `/usr/share/vocabs`.

**Comment by ijdickinson** [comment]
Good to hear about the forthcoming 1.0. I'll look forward to that :smile: 

For the time being, I've implemented the `/usr/share/vocabs` workaround, so I'm not blocked.

> PS: To my excuse, the very hacky implementation of the vocabulary namespaces were my first experience with using macros in Elixir back in the day and the long overdue major overhaul was the last thing holding me back from a version 1.0.

From my point of view, anyone who's willing to create and maintain a useful open-source package like RDF.ex only deserves credit and our gratitude. No excuses are needed!

**Comment by marcelotto** [comment]
> My app has a GenServer application that reads some static files when it starts up.

In order to ensure your use case will be supported with the new version, could you share the code from the mentioned GenServer where it is doing the failing read attempt.

**Comment by marcelotto** [comment]
RDF.ex 1.0 was released yesterday and should provide capabilities to fix your problem. All generated vocabulary namespaces now have a `__file__/0` function which returns the path to the specified file relative to `:code.priv_dir`. For more, read the updated guide [here](https://rdf-elixir.dev/rdf-ex/namespaces.html).

Could please confirm that everything works now, so we can close this issue?
