### ISSUE TITLE
Unexpected dialyzer warnings from `defvocab`

### ISSUE THREAD

**Issue by ijdickinson** [rdf-elixir/rdf-ex#18]
I'm getting dialyzer warnings fom all of my `defvocab` terms. For example, this definition:

```elixir
  defvocab(Qudt,
    base_iri: "http://qudt.org/schema/qudt/",
    terms: [:value, :unit]
  )
```

produces:

```
lib/myproject/ns.ex:55:extra_range
The type specification has too many types for the function.

Function:
Ecas.Metric31.NS.QudtVocab.__strict__/0

Extra type:
true

Success typing:
false
```

All of the warnings I'm getting involve `__strict__`. Sometimes the success typing is `true`, and sometimes it's `false`.

**Comment by marcelotto** [comment]
That's strange. Never happened to me. I'll look into this as soon as possible.

**Comment by marcelotto** [comment]
Unfortunately, I'm not able to reproduce the problem. I've defined the exact same namespace, you've provided and don't get any dialyzer warning. Could you please provide a minimal example that produces the warning.

Does this warning actually relate to given defvocab definition? Neither the module name (`Ecas.Metric31.NS.QudtVocab`) nor the term (`extra_range`) matches anything from this definition.

**Comment by ijdickinson** [comment]
Thanks for looking into this. Sorry about the module name, I tried to anonymise the report from my actual project (but clearly not well enough :smile: )

I checked the problem in a newly-generated Elixir project. I also couldn't repro the error at first, until I copied our exact Dialyzer config. Adding the `unknown` flag to the Dialyzer config:

```
  # mix.exs
      dialyzer: [
        flags: [
          :unknown,
        ]
      ],
```

triggers the problem.

We have a number of additional Dialyzer flags set by default, `unknown` is the only one that triggered this warning.

**Comment by marcelotto** [comment]
I've also created a clean project with just this:

```elixir
defmodule DialyzerTest do
  use RDF.Vocabulary.Namespace

  defvocab(Qudt,
    base_iri: "http://qudt.org/schema/qudt/",
    terms: [:value, :unit]
  )
end
```
and the dialyzer config in my Mixfile, but I still don't get this warning.

I'm running with the following versions:

- Erlang 25.1
- Elixir 1.4.3
- RDF.ex 1.1.1
- Dialyxir 1.3.0

BTW: From looking at the output of `mix dialyzer` it seems the `unknown` option is enabled by default with Dialyxir (as opposed to pure Dialyzer where it's disabled by default). When I add the flag in the Mixfile I just see the `:unknown` value twice in the `warnings` config shown during the run.

**Comment by marcelotto** [comment]
Any news on the issue?

**Comment by ijdickinson** [comment]
Sorry, I should have updated the ticket. I can't easily reproduce it. I'll close the issue, and we can always re-open if I find a way to provoke it in a repeatable way.
