### ISSUE TITLE
New String.slice/2 compiler warnings in Elixir 1.16

### ISSUE THREAD

**Issue by shanesveller** [rdf-elixir/rdf-ex#20]
In Elixir 1.16.0, [Enum and String.slice have deprecated negative steps](https://hexdocs.pm/elixir/1.16.0/changelog.html#4-hard-deprecations), producing compiler warnings like so:

```
warning: negative steps are not supported in String.slice/2, pass 1..-2//1 instead
  (elixir 1.16.1) lib/string.ex:2369: String.slice/2
  (rdf 1.2.0-pre) src/turtle_lexer.xrl:57: :turtle_lexer.yyaction/5
  (rdf 1.2.0-pre) /nix/store/72wc42ldfa706klwyah3hdwsvlpwwp5m-erlang-26.2.1/lib/erlang/lib/parsetools-2.5/include/leexinc.hrl:43: :turtle_lexer.do_string/5
  (rdf 1.2.0-pre) /nix/store/72wc42ldfa706klwyah3hdwsvlpwwp5m-erlang-26.2.1/lib/erlang/lib/parsetools-2.5/include/leexinc.hrl:30: :turtle_lexer.string/5
  (rdf 1.2.0-pre) lib/rdf/serializations/turtle/decoder.ex:51: RDF.Turtle.Decoder.decode/2
  (rdf 1.2.0-pre) lib/rdf/serializations/turtle/decoder.ex:17: RDF.Turtle.Decoder.decode!/2
```

The current tip of `master` produces about ~4200 lines worth of the above on my own project during `mix deps.compile`.

Is there anything I can do to help with addressing these?

**Comment by marcelotto** [comment]
I'm actually in the process of adding support for newer Elixir versions at this very moment.

**Comment by marcelotto** [comment]
Fixed on master. However, the release has to wait due to some ongoing work that should be included in the next version.
